import { AuditReport } from './types';
import { simulateDeviceThrottling } from './mobileSimulator';
import { UNOVA_MULTIPAGE_BENCHMARK } from './spiderCrawler';
import { evaluateUATAcceptance } from './uatAuditor';

const UNOVA_ROOT_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <title>Unova | Engineering Firm for High-Performance Websites & Systems</title>
  <meta name="description" content="Unova is an engineering firm for teams who need the surface to be beautiful and the substructure to be correct. Websites, applications, internal systems, AI integration.">
  <link rel="canonical" href="https://unova.co.in">
</head>
<body>
  <header>
    <a href="/about">About</a>
    <a href="/services">Services</a>
    <a href="/pricing">Pricing</a>
    <a href="/contact">Start a project</a>
  </header>
  <main>
    <h1>We build what people are searching for.</h1>
    <p>Unova is an engineering firm for teams who need the surface to be beautiful and the substructure to be correct.</p>
    <a href="/contact" class="btn-primary">Start a project</a>
    <a href="/showcase" class="btn-secondary">See the work</a>
  </main>
  <footer>
    <a href="/privacy-policy">Privacy Policy</a>
    <a href="/terms">Terms of Service</a>
  </footer>
</body>
</html>`;

export const DEMO_PRESETS: Record<string, AuditReport> = {
  'unova-benchmark': {
    id: 'preset-unova-benchmark',
    timestamp: new Date().toISOString(),
    targetUrl: 'https://unova.co.in',
    finalUrl: 'https://unova.co.in',
    crawlScope: 'multi-page-spider',
    overallScore: 79,
    scores: {
      coreWebVitals: 80,
      seoAndIndexability: 82,
      linkCompliance: 86,
      securityPosture: 66,
      codeAndDomHealth: 74,
      frontendAndUx: 88,
    },
    coreWebVitals: {
      lcp: {
        value: 2.45,
        unit: 's',
        rating: 'needs-improvement',
        threshold: { good: 2.5, poor: 4.0 },
        breakdown: {
          ttfbMs: 340,
          resourceLoadDelayMs: 410,
          resourceLoadTimeMs: 1100,
          elementRenderDelayMs: 600,
        },
        candidateElement: 'Hero Canvas / Background Video',
        details: 'Initial canvas WebGL shader init and custom typography slightly delay Largest Contentful Paint under 6x CPU.',
      },
      inp: {
        value: 160,
        unit: 'ms',
        rating: 'good',
        threshold: { good: 200, poor: 500 },
        breakdown: {
          inputDelayMs: 35,
          processingDurationMs: 85,
          presentationDelayMs: 40,
          longTaskEstimatedCount: 3,
          totalDomNodes: 1240,
        },
        details: 'Interaction response remains within Google 200ms threshold.',
      },
      cls: {
        value: 0.04,
        unit: 'score',
        rating: 'good',
        threshold: { good: 0.1, poor: 0.25 },
        breakdown: {
          unsizedImagesCount: 1,
          unsizedIframesCount: 0,
          webFontsShiftRisk: 'Low',
        },
        details: 'Stable visual layout during viewport loading.',
      },
      fcp: {
        value: 3.12,
        unit: 's',
        rating: 'poor',
        threshold: { good: 1.8, poor: 3.0 },
        breakdown: {
          renderBlockingStyles: 2,
          renderBlockingScripts: 1,
          fontParsingDelayMs: 240,
        },
        details: 'FCP is 3120ms under mobile throttling, triggered by web font resolution and script bundling.',
      },
      ttfb: {
        value: 340,
        unit: 'ms',
        rating: 'good',
        threshold: { good: 800, poor: 1800 },
        breakdown: {
          dnsLookupMs: 35,
          tcpHandshakeMs: 65,
          tlsNegotiationMs: 80,
          serverProcessingMs: 160,
        },
        details: 'Edge CDN delivers initial HTML within 340ms.',
      },
    },
    searchEssentials: {
      status: 200,
      isIndexable: true,
      hasRobotsTxt: true,
      robotsTxtUrl: 'https://unova.co.in/robots.txt',
      robotsDirectives: {
        userAgent: '*',
        disallow: ['/api/'],
        allow: ['/'],
        sitemaps: ['https://unova.co.in/sitemap.xml'],
      },
      metaRobots: 'index, follow',
      canonicalUrl: 'https://unova.co.in',
      isCanonicalSelfReferencing: true,
      canonicalStatus: 'valid',
      hasSitemap: true,
      sitemapUrl: 'https://unova.co.in/sitemap.xml',
      headingStructure: {
        h1Count: 1,
        h1Texts: ['Unova // Engineering Next-Generation Digital Experiences'],
        h2Count: 8,
        hasHierarchyIssues: false,
        hierarchyWarnings: [],
      },
      structuredData: {
        hasJsonLd: true,
        types: ['Organization', 'WebSite'],
        validSyntax: true,
        errors: [],
      },
      mobileViewport: {
        hasTag: true,
        content: 'width=device-width, initial-scale=1.0',
        isCompliant: true,
      },
      openGraph: {
        title: 'Unova // Creative Technology & Systems',
        description: 'Elite digital architecture and product engineering.',
      },
      hreflang: [{ lang: 'en', href: 'https://unova.co.in' }],
    },
    linkAudit: {
      totalLinks: 48,
      crawlableLinksCount: 46,
      nonCrawlableLinksCount: 2,
      internalLinksCount: 38,
      externalLinksCount: 10,
      genericAnchorCount: 3,
      score: 86,
      genericAnchorViolations: [
        {
          href: 'https://unova.co.in/case-studies',
          anchorText: 'Read more',
          flaggedReason: 'Non-descriptive anchor text violates Google Search Essentials.',
          suggestion: 'Replace with descriptive text such as "Explore our fintech case studies".',
        },
      ],
      nonCrawlableViolations: [
        {
          tag: 'a',
          elementHtml: '<a href="javascript:void(0)" class="filter-btn">All</a>',
          violation: 'javascript-void',
          remediation: 'Use a standard button or real URL for filter navigation.',
        },
      ],
      links: [],
    },
    security: {
      score: 66,
      findings: [
        {
          id: 'missing-csp',
          title: 'Content-Security-Policy (CSP) Header Missing',
          severity: 'high',
          category: 'A05:2021 Security Misconfiguration',
          cvss: 6.5,
          evidence: 'No CSP header present across 13 audited routes.',
          remediation: 'Add Content-Security-Policy header in edge proxy or Next.js headers.',
        },
        {
          id: 'missing-hsts-preload',
          title: 'Strict-Transport-Security (HSTS) Missing Preload Directive',
          severity: 'medium',
          category: 'A05:2021 Security Misconfiguration',
          cvss: 5.3,
          evidence: 'HSTS header does not include "preload" flag.',
          remediation: 'Append preload to HSTS directive.',
        },
        {
          id: 'missing-x-frame-options',
          title: 'X-Frame-Options Missing on Sub-routes',
          severity: 'medium',
          category: 'A05:2021 Security Misconfiguration',
          cvss: 5.4,
          evidence: 'Frame protection missing on /about, /services, and /solutions.',
          remediation: 'Configure X-Frame-Options: SAMEORIGIN.',
        },
      ],
      headersInspected: {
        'server': 'cloudflare',
        'x-content-type-options': 'nosniff',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
      },
      tlsStatus: {
        isHttps: true,
        hstsPreloaded: false,
        mixedContentDetected: false,
      },
    },
    deepBugs: {
      hydrationMismatches: [],
      brokenDomStates: [
        {
          id: 'duplicate-id-grid',
          severity: 'medium',
          type: 'duplicate-id',
          element: 'id="feature-card"',
          description: 'Duplicate ID attribute on repeated card elements in grid.',
          remediation: 'Convert feature-card from id to class attribute.',
        },
      ],
      memoryLeakHeuristics: {
        domNodeCount: 1240,
        domNodeStatus: 'healthy',
        listenerAccumulationRisk: 'low',
        jsHeapEstimatedMb: 38,
        findings: ['1,240 DOM nodes - clean DOM hierarchy.'],
      },
      consoleErrors: [],
    },
    mobileThrottling: {
      id: 'budget-2gb',
      name: 'Budget Mobile (2GB RAM / 6x CPU Slowdown)',
      cpuSlowdown: 6,
      memoryRamGb: 2,
      networkType: 'slow-4g',
      downloadThroughputKbps: 1600,
      uploadThroughputKbps: 750,
      latencyMs: 150,
      simulation: {
        lcpMultiplier: 3.2,
        inpMultiplier: 2.8,
        mainThreadScriptingMs: 2400,
        mainThreadRenderingMs: 950,
        mainThreadPaintingMs: 420,
        networkWaitMs: 3800,
        totalLoadTimeSec: 10.22,
        status: 'Critical (Device Starvation)',
      },
    },
    spiderArchitecture: UNOVA_MULTIPAGE_BENCHMARK,
    frontendDiagnostics: {
      score: 88,
      colorPsychology: {
        score: 92,
        palette: [
          {
            hex: '#fbf9f4',
            percentage: 60,
            role: 'dominant-60',
            emotion: 'Clarity, Spaciousness & Cognitive Openness',
            archetype: 'Open Canvas & Perceptual Ease',
            autonomicEffect: 'Parasympathetic Restorative',
          },
          {
            hex: '#1e1e24',
            percentage: 30,
            role: 'secondary-30',
            emotion: 'Calligraphy Gravity, Formality & Contrast',
            archetype: 'Boundary Definition & High Contrast',
            autonomicEffect: 'Neutral/Equilibrium',
          },
          {
            hex: '#7d598f',
            percentage: 10,
            role: 'accent-10',
            emotion: 'Refinement, Creativity & Technological Elegance',
            archetype: 'Imaginative Focus',
            autonomicEffect: 'Neutral/Equilibrium',
          },
        ],
        apcaContrast: {
          score: 94,
          passingCount: 4,
          failingCount: 0,
          samples: [
            {
              fg: '#1e1e24',
              bg: '#fbf9f4',
              ratio: 14.8,
              apcaLc: 96.2,
              status: 'AAA',
              textSample: 'Primary Typography: Unova Spider Engine',
            },
            {
              fg: '#44403c',
              bg: '#fbf9f4',
              ratio: 9.6,
              apcaLc: 78.4,
              status: 'AAA',
              textSample: 'Body Narrative & Diagnostic Heuristics',
            },
            {
              fg: '#7d598f',
              bg: '#fbf9f4',
              ratio: 5.2,
              apcaLc: 62.1,
              status: 'AA',
              textSample: 'Accent Badges & Kinetic Indicators',
            },
            {
              fg: '#ffffff',
              bg: '#1e1e24',
              ratio: 15.2,
              apcaLc: 98.4,
              status: 'AAA',
              textSample: 'Inverse Button CTA & High-Contrast Pills',
            },
          ],
        },
        saliencyVsComfort: {
          saliencyScore: 84,
          comfortScore: 92,
          congruenceRating: 'High Alignment',
          insight: 'Eye-tracking saliency matches user intentional goals without intrusive jarring contrast spikes (Song et al. 2021).',
        },
        kobayashiMood: 'Peaceful, Natural & Modern',
      },
      typography: {
        score: 90,
        fontCount: 2,
        fonts: ['Geist Sans', 'Geist Mono', 'Inter'],
        hierarchyCompliant: true,
        lineHeightRatio: 1.55,
        lineMeasureCh: 62,
        issues: ['Minor: ensure secondary subtitles maintain 14px floor on mobile viewports.'],
      },
      layoutAndMobile: {
        score: 86,
        touchTargetsPassed: 18,
        touchTargetsSubstandard: 1,
        horizontalOverflow: false,
        spacingGridCompliant: true,
        issues: ['Footer newsletter submit button is 40px height; recommend padding to 48px.'],
      },
      animationAndMotion: {
        score: 92,
        averageDurationMs: 280,
        prefersReducedMotionSupported: true,
        infiniteLoopsDetected: 0,
        hardwareAccelerated: true,
        issues: [],
      },
    },
    uatAcceptance: evaluateUATAcceptance({
      html: UNOVA_ROOT_HTML,
      targetUrl: 'https://unova.co.in',
      spiderArchitecture: UNOVA_MULTIPAGE_BENCHMARK,
      mobileLoadTimeSec: 3.12,
      mobileFcpMs: 1230,
      securityScore: 66,
      securityFindingsCount: 6,
      brokenImagesCount: 0,
      accessibilityViolationsCount: 1,
      ttfbMs: 340,
      lcpMs: 2450,
    }),
  },
  'nextjs-saas': {
    id: 'preset-nextjs-saas',
    timestamp: new Date().toISOString(),
    targetUrl: 'https://acme-cloud.io',
    finalUrl: 'https://acme-cloud.io',
    overallScore: 88,
    scores: {
      coreWebVitals: 92,
      seoAndIndexability: 96,
      linkCompliance: 94,
      securityPosture: 78,
      codeAndDomHealth: 82,
    },
    coreWebVitals: {
      lcp: {
        value: 1.45,
        unit: 's',
        rating: 'good',
        threshold: { good: 2.5, poor: 4.0 },
        breakdown: {
          ttfbMs: 140,
          resourceLoadDelayMs: 220,
          resourceLoadTimeMs: 650,
          elementRenderDelayMs: 440,
        },
        candidateElement: 'Hero Banner: <img src="/assets/hero-cloud-dashboard.webp">',
        details: 'Optimal Largest Contentful Paint. WebP format and priority preloading ensure quick hero rendering.',
      },
      inp: {
        value: 120,
        unit: 'ms',
        rating: 'good',
        threshold: { good: 200, poor: 500 },
        breakdown: {
          inputDelayMs: 28,
          processingDurationMs: 62,
          presentationDelayMs: 30,
          longTaskEstimatedCount: 1,
          totalDomNodes: 680,
        },
        details: 'Low input latency. User interaction handlers respond well within Google 200ms threshold.',
      },
      cls: {
        value: 0.02,
        unit: 'score',
        rating: 'good',
        threshold: { good: 0.1, poor: 0.25 },
        breakdown: {
          unsizedImagesCount: 0,
          unsizedIframesCount: 0,
          webFontsShiftRisk: 'Low',
        },
        details: 'Zero layout shift detected during initial viewport rendering.',
      },
      fcp: {
        value: 0.95,
        unit: 's',
        rating: 'good',
        threshold: { good: 1.8, poor: 3.0 },
        breakdown: {
          renderBlockingStyles: 1,
          renderBlockingScripts: 0,
          fontParsingDelayMs: 60,
        },
        details: 'Streamlined critical CSS enables fast first contentful paint.',
      },
      ttfb: {
        value: 0.14,
        unit: 's',
        rating: 'good',
        threshold: { good: 0.8, poor: 1.8 },
        breakdown: {
          dnsLookupMs: 22,
          tcpHandshakeMs: 35,
          sslNegotiationMs: 43,
          serverExecutionMs: 40,
        },
        details: 'Edge CDN caching provides sub-200ms initial document delivery.',
      },
    },
    searchEssentials: {
      status: 200,
      isIndexable: true,
      hasRobotsTxt: true,
      robotsTxtUrl: 'https://acme-cloud.io/robots.txt',
      robotsDirectives: {
        userAgent: '*',
        disallow: ['/api/', '/admin/'],
        allow: ['/'],
        sitemaps: ['https://acme-cloud.io/sitemap.xml'],
      },
      metaRobots: 'index, follow',
      canonicalUrl: 'https://acme-cloud.io',
      isCanonicalSelfReferencing: true,
      canonicalStatus: 'valid',
      hasSitemap: true,
      sitemapUrl: 'https://acme-cloud.io/sitemap.xml',
      headingStructure: {
        h1Count: 1,
        h1Texts: ['Enterprise Cloud Orchestration Platform'],
        h2Count: 6,
        hasHierarchyIssues: false,
        hierarchyWarnings: [],
      },
      structuredData: {
        hasJsonLd: true,
        types: ['SoftwareApplication', 'Organization'],
        validSyntax: true,
        errors: [],
      },
      mobileViewport: {
        hasTag: true,
        content: 'width=device-width, initial-scale=1.0',
        isCompliant: true,
      },
      openGraph: {
        title: 'Acme Cloud - Enterprise Cloud Orchestration',
        description: 'Automate infrastructure and observability across multicloud clusters.',
        image: 'https://acme-cloud.io/og-image.png',
      },
      hreflang: [
        { lang: 'en', href: 'https://acme-cloud.io' },
        { lang: 'de', href: 'https://acme-cloud.io/de' },
      ],
    },
    linkAudit: {
      totalLinks: 42,
      crawlableLinksCount: 40,
      nonCrawlableLinksCount: 2,
      internalLinksCount: 32,
      externalLinksCount: 10,
      genericAnchorCount: 2,
      score: 94,
      genericAnchorViolations: [
        {
          href: 'https://acme-cloud.io/features/security',
          anchorText: 'Learn more',
          flaggedReason: 'Generic anchor text violates Google Search Essentials. Crawlers cannot infer page context from vague text.',
          suggestion: 'Replace "Learn more" with descriptive keywords: "Explore enterprise cloud security features".',
          contextSnippet: '<a href="/features/security" class="text-blue-500">Learn more &rarr;</a>',
        },
        {
          href: 'https://acme-cloud.io/docs/quickstart',
          anchorText: 'click here',
          flaggedReason: 'Generic anchor text violates Google Search Essentials. Crawlers cannot infer page context from vague text.',
          suggestion: 'Replace "click here" with descriptive keywords: "View developer quickstart guide".',
          contextSnippet: '<p>To get started with our CLI, <a href="/docs/quickstart">click here</a>.</p>',
        },
      ],
      nonCrawlableViolations: [
        {
          tag: 'a',
          elementHtml: '<a href="javascript:void(0)" onclick="openModal()">Contact Sales</a>',
          violation: 'javascript-void',
          remediation: 'Replace javascript:void(0) pseudo-URL with a semantic <button> or modal deep-link route.',
        },
      ],
      links: [
        {
          href: 'https://acme-cloud.io/pricing',
          text: 'Pricing & Plans',
          type: 'internal',
          isCrawlable: true,
          isGenericText: false,
          rel: [],
          isSecure: true,
        },
        {
          href: 'https://github.com/acme/sdk',
          text: 'Acme Open Source SDK',
          type: 'external',
          isCrawlable: true,
          isGenericText: false,
          rel: ['noopener', 'noreferrer'],
          isSecure: true,
        },
      ],
    },
    security: {
      score: 78,
      findings: [
        {
          id: 'missing-csp',
          title: 'Content-Security-Policy (CSP) Header Missing',
          severity: 'high',
          category: 'A05:2021 Security Misconfiguration',
          cvss: 6.5,
          evidence: 'No Content-Security-Policy HTTP response header found on the page.',
          remediation: "Deploy a Content-Security-Policy with default-src 'self' to mitigate XSS and unauthorized script injection.",
          remediationCode: {
            nextConfig: `// next.config.js\nmodule.exports = {\n  async headers() {\n    return [{\n      source: '/(.*)',\n      headers: [{\n        key: 'Content-Security-Policy',\n        value: "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"\n      }]\n    }];\n  }\n};`,
          },
        },
        {
          id: 'missing-permissions-policy',
          title: 'Permissions-Policy Header Missing',
          severity: 'info',
          category: 'A05:2021 Security Misconfiguration',
          cvss: null,
          evidence: 'No Permissions-Policy header found to explicitly control browser hardware capabilities.',
          remediation: 'Define Permissions-Policy: camera=(), microphone=(), geolocation=().',
        },
      ],
      headersInspected: {
        'strict-transport-security': 'max-age=63072000; includeSubDomains; preload',
        'x-content-type-options': 'nosniff',
        'x-frame-options': 'DENY',
        'referrer-policy': 'strict-origin-when-cross-origin',
      },
      tlsStatus: {
        isHttps: true,
        hstsPreloaded: true,
        mixedContentDetected: false,
      },
    },
    deepBugs: {
      hydrationMismatches: [
        {
          id: 'hydration-nesting-1',
          component: 'Header / Nav',
          element: '<p class="text-xs text-gray-500"><div>Badge</div></p>',
          errorType: 'invalid-nesting',
          description: 'Illegal HTML Nesting: Block <div> element nested inside a <p> tag, causing client DOM mismatch during React hydration.',
          suggestedFix: 'Replace the parent <p> element with a <div> or wrap the badge in a <span> tag.',
        },
      ],
      brokenDomStates: [
        {
          id: 'broken-dom-missing-alt-1',
          severity: 'medium',
          type: 'missing-alt',
          element: '<img src="/assets/icons/cloud-speed.svg">',
          description: 'Image missing alt attribute. Screen readers cannot describe the asset to assistive technology users.',
          remediation: 'Provide descriptive alt text for informative graphics or alt="" for decorative assets.',
        },
      ],
      memoryLeakHeuristics: {
        domNodeCount: 680,
        domNodeStatus: 'healthy',
        listenerAccumulationRisk: 'low',
        jsHeapEstimatedMb: 24,
        findings: [],
      },
      consoleErrors: [],
    },
    mobileThrottling: simulateDeviceThrottling('budget-2gb', 1.45, 120, 680),
  },

  'ecommerce-heavy': {
    id: 'preset-ecommerce-heavy',
    timestamp: new Date().toISOString(),
    targetUrl: 'https://megamart-global.shop',
    finalUrl: 'https://megamart-global.shop',
    overallScore: 54,
    scores: {
      coreWebVitals: 48,
      seoAndIndexability: 74,
      linkCompliance: 62,
      securityPosture: 50,
      codeAndDomHealth: 42,
    },
    coreWebVitals: {
      lcp: {
        value: 4.82,
        unit: 's',
        rating: 'poor',
        threshold: { good: 2.5, poor: 4.0 },
        breakdown: {
          ttfbMs: 820,
          resourceLoadDelayMs: 950,
          resourceLoadTimeMs: 2150,
          elementRenderDelayMs: 900,
        },
        candidateElement: 'Carousel Image: <img src="/cdn/hero/summer-sale-huge.jpg"> (3.4 MB unoptimized JPEG)',
        details: 'Severe LCP bottleneck: 3.4 MB hero image loaded without responsive sizes or modern WebP/AVIF compression.',
      },
      inp: {
        value: 540,
        unit: 'ms',
        rating: 'poor',
        threshold: { good: 200, poor: 500 },
        breakdown: {
          inputDelayMs: 140,
          processingDurationMs: 290,
          presentationDelayMs: 110,
          longTaskEstimatedCount: 14,
          totalDomNodes: 3450,
        },
        details: 'Severe main-thread contention caused by 14 third-party analytics/tracking tag managers and 3,450 DOM elements.',
      },
      cls: {
        value: 0.38,
        unit: 'score',
        rating: 'poor',
        threshold: { good: 0.1, poor: 0.25 },
        breakdown: {
          unsizedImagesCount: 18,
          unsizedIframesCount: 3,
          webFontsShiftRisk: 'High (FOUT/FOIT)',
        },
        details: 'Dynamic promotional banner and 18 unsized product thumbnails inject sudden layout shifts during image decode.',
      },
      fcp: {
        value: 2.9,
        unit: 's',
        rating: 'needs-improvement',
        threshold: { good: 1.8, poor: 3.0 },
        breakdown: {
          renderBlockingStyles: 6,
          renderBlockingScripts: 4,
          fontParsingDelayMs: 380,
        },
        details: 'Heavy external CSS and sync tag scripts block initial paint.',
      },
      ttfb: {
        value: 0.82,
        unit: 's',
        rating: 'needs-improvement',
        threshold: { good: 0.8, poor: 1.8 },
        breakdown: {
          dnsLookupMs: 110,
          tcpHandshakeMs: 160,
          sslNegotiationMs: 230,
          serverExecutionMs: 320,
        },
        details: 'Database queries on product catalog delay initial server response.',
      },
    },
    searchEssentials: {
      status: 200,
      isIndexable: true,
      hasRobotsTxt: true,
      robotsTxtUrl: 'https://megamart-global.shop/robots.txt',
      robotsDirectives: {
        userAgent: '*',
        disallow: ['/cart', '/checkout', '/account'],
        allow: ['/products'],
        sitemaps: ['https://megamart-global.shop/sitemap-products.xml'],
      },
      metaRobots: 'index, follow',
      canonicalUrl: 'https://megamart-global.shop/?ref=partner-campaign',
      isCanonicalSelfReferencing: false,
      canonicalStatus: 'mismatch',
      hasSitemap: true,
      sitemapUrl: 'https://megamart-global.shop/sitemap-products.xml',
      headingStructure: {
        h1Count: 0,
        h1Texts: [],
        h2Count: 14,
        hasHierarchyIssues: true,
        hierarchyWarnings: ['Missing <h1> heading tag. Google requires a primary document heading.', 'Skipped primary heading: <h2> exists without preceding <h1>.'],
      },
      structuredData: {
        hasJsonLd: true,
        types: ['Product'],
        validSyntax: false,
        errors: ['JSON-LD Syntax Error: Missing required field "offers.priceCurrency" in Product schema.'],
      },
      mobileViewport: {
        hasTag: true,
        content: 'width=device-width, initial-scale=1.0',
        isCompliant: true,
      },
      openGraph: {
        title: 'MegaMart Global Deals',
        description: 'Save up to 70% on consumer electronics and home apparel.',
      },
      hreflang: [],
    },
    linkAudit: {
      totalLinks: 184,
      crawlableLinksCount: 142,
      nonCrawlableLinksCount: 42,
      internalLinksCount: 160,
      externalLinksCount: 24,
      genericAnchorCount: 38,
      score: 62,
      genericAnchorViolations: [
        {
          href: 'https://megamart-global.shop/deals/flash',
          anchorText: 'click here',
          flaggedReason: 'Generic anchor text violates Google Search Essentials.',
          suggestion: 'Replace "click here" with "Shop daily flash clearance deals".',
          contextSnippet: '<p>Don\'t miss out! <a href="/deals/flash">click here</a></p>',
        },
        {
          href: 'https://megamart-global.shop/categories/apparel',
          anchorText: 'read more',
          flaggedReason: 'Generic anchor text violates Google Search Essentials.',
          suggestion: 'Replace "read more" with "Browse summer apparel collection".',
          contextSnippet: '<span>Trending Fashion Trends <a href="/categories/apparel">read more</a></span>',
        },
      ],
      nonCrawlableViolations: [
        {
          tag: 'div',
          elementHtml: '<div onclick="window.location=\'/cart\'" class="btn-cart">Add to Cart</div>',
          violation: 'onclick-without-href',
          remediation: 'Convert to standard form action or crawlable anchor element so search engines understand navigation hierarchy.',
        },
      ],
      links: [],
    },
    security: {
      score: 50,
      findings: [
        {
          id: 'missing-csp',
          title: 'Content-Security-Policy (CSP) Header Missing',
          severity: 'high',
          category: 'A05:2021 Security Misconfiguration',
          cvss: 6.5,
          evidence: 'No CSP configured. Storefront vulnerable to third-party script tampering (Magecart style injection).',
          remediation: 'Implement a strict CSP restricting script execution to approved CDNs.',
        },
        {
          id: 'clickjacking-vulnerability',
          title: 'Clickjacking Protection Missing',
          severity: 'medium',
          category: 'A05:2021 Security Misconfiguration',
          cvss: 5.4,
          evidence: 'Neither X-Frame-Options nor frame-ancestors is present.',
          remediation: 'Add X-Frame-Options: SAMEORIGIN or CSP frame-ancestors to prevent checkout embedding.',
        },
        {
          id: 'missing-nosniff',
          title: 'MIME-Type Sniffing Protection Missing (X-Content-Type-Options)',
          severity: 'low',
          category: 'A05:2021 Security Misconfiguration',
          cvss: 3.4,
          evidence: 'X-Content-Type-Options header is absent.',
          remediation: 'Set X-Content-Type-Options: nosniff.',
        },
      ],
      headersInspected: {
        'server': 'nginx/1.18.0 (Ubuntu)',
        'x-powered-by': 'PHP/8.1.12',
      },
      tlsStatus: {
        isHttps: true,
        hstsPreloaded: false,
        mixedContentDetected: true,
      },
    },
    deepBugs: {
      hydrationMismatches: [
        {
          id: 'hydration-cart-count',
          component: 'MiniCartHeader',
          element: '<span class="badge">0</span> (Server) vs <span class="badge">3</span> (Client)',
          errorType: 'server-client-mismatch',
          description: 'Client/Server Hydration Mismatch: Cart count read from localStorage differs from SSR HTML, causing hydration bailout.',
          suggestedFix: 'Initialize cart state after component mount in a useEffect hook or use dynamic rendering with ssr: false.',
        },
      ],
      brokenDomStates: [
        {
          id: 'broken-dom-duplicate-id-search',
          severity: 'high',
          type: 'duplicate-id',
          element: 'id="search-input" (appears 3 times in header, mobile drawer, and footer)',
          description: 'Duplicate ID attribute breaks screen reader aria-controls mapping.',
          remediation: 'Ensure ID attributes are globally unique.',
        },
        {
          id: 'broken-dom-empty-button-cart',
          severity: 'high',
          type: 'missing-button-name',
          element: '<button class="cart-icon"><svg>...</svg></button>',
          description: 'Interactive button missing accessible name.',
          remediation: 'Add aria-label="View Shopping Cart".',
        },
      ],
      memoryLeakHeuristics: {
        domNodeCount: 3450,
        domNodeStatus: 'critical',
        listenerAccumulationRisk: 'high',
        jsHeapEstimatedMb: 82,
        findings: [
          'High DOM tree complexity: 3450 elements present. Severe memory consumption on low-end devices.',
          'Heavy JavaScript footprint: 48 script tags loaded across third-party marketing tags.',
        ],
      },
      consoleErrors: [
        {
          type: 'error',
          message: 'Uncaught TypeError: Cannot read property "dataLayer" of undefined at analytics-gtm.js:14',
          source: 'https://tagservices.external/analytics-gtm.js',
        },
      ],
    },
    mobileThrottling: simulateDeviceThrottling('budget-2gb', 4.82, 540, 3450),
  },
};
